{
 "title": "Relatorios",
 "time": { "from": "2025-10-09T00:02:24.015Z", "to": "2025-10-09T00:02:33.334Z" },
 "panels": [
  {
   "title": "Total de exceções lançadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(type) (system_runtime_exception_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições recebidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code) (http_requests_received_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de GCs por geração",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(dotnet_collection_count_total{generation=\"0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência das requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, http_request_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória RAM usada pelo processo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU consumida pelo processo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}